-- INSTALL OBJECTS...
\c "QUALITYAPP_BD" 

\i 01_SECUENCIAS/INSTALL_SECUENCIAS.sql
\i 02_TABLAS/INSTALL_TABLAS.sql
\i 03_PRIMARY_KEY/INSTALL_PKS.sql
\i 03_ALTERS/INSTALL_ALTERS.sql
\i 04_TIPOS/INSTALL_TIPOS.sql
\i 05_VISTAS/INSTALL_VISTAS.sql
\i 06_FUNCIONES/INSTALL_FUNCIONES.sql

\i 07_DATOS/INSTALL_DATOS.sql
\i 03_FOREIGN_KEY/INSTALL_FOREIGN.sql
\i 03_CONSTRAINTS/INSTALL_CONS.sql
\i 08_CHECKS/INSTALL_CHECKS.sql

