services:
  auth_service:
    build:
        context: ./auth_service
    container_name: auth_service
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/auth/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  quality_service:
    build:
        context: ./quality_service
    container_name: quality_service
    ports:
      - "5001:5001"
    env_file:
      - .env
    restart: always
    depends_on:
      auth_service:
        condition: service_healthy
